### ISSUE TITLE
Add support of customised HTTP client

### ISSUE THREAD

**Issue by maidmaid** [lmerotta/phpokeapi#1]
Why not add the support for a customised HTTP client ? Currently, the client internally uses the curl extension into its `sendRequest()` method and we could add more flexibility by adding the support of a `HttpClient` interface brought by [HTTPlug](http://docs.php-http.org/en/latest/httplug/introduction.html#client-interfaces).

```php
public function __construct(string $url = 'https://pokeapi.co/api/v2/', CacheInterface $cache = null, SerializerInterface $serializer = null, HttpClient $httpClient = null)
```

**Comment by lmerotta-zz** [comment]
Sure! If you submit a PR I'd be glad to review it 😄
