### ISSUE TITLE
Expected metadata for class PokeAPI\Pokemon\VersionHeldItem

### ISSUE THREAD

**Issue by Gamer2020** [lmerotta/phpokeapi#7]
When using the below:

$client = new Client();
$pokemon = $client->Pokemon($id);

Some Pokemon return the following.

Message: Expected metadata for class PokeAPI\Pokemon\VersionHeldItem to be defined in /home/xnkluper/public_html/dexter/wp-content/plugins/dexter/vendor/lmerotta/phpokeapi/src/JMS/Serializer/../config/PokeAPI.Pokemon.VersionHeldItem.yml.

Example: http://dexter.gamer2020.net/pokemon/?ID=116

Working example: http://dexter.gamer2020.net/pokemon/?ID=115

**Comment by lmerotta-zz** [comment]
Hm, it seems I've made a small mistake when creating the YAML definition for VersionHeldItem. I'll work on it, thanks for your feedback !

**Comment by Gamer2020** [comment]
Thank you!

**Comment by jeroenbalk-adwise** [comment]
Is this hard to fix?

Because I'm trying to make some kind of search function, and a whole lot of api calls result in an error because of this yaml. Hope to see a fix soon :)

Thanks in advance.

**Comment by lmerotta-zz** [comment]
Hi @Gamer2020 and @jeroenbalk-adwise, this has just been fixed in version 1.1.5, you can update your dependencies and keep on using phpokeapi ! Thank you for your patience 😄

**Comment by jeroenbalk-adwise** [comment]
Nice! Thanks :)! I'm gonna update! Keep up the good work! :)

**Comment by Gamer2020** [comment]
I confirm that it is fixed. Thank you!
